parameters:
- name: PackageApp
  displayName: Package App
  type: boolean
  default: true

- name: PackageACTests
  displayName: Package Acceptance Tests
  type: boolean
  default: false

- name: PackageNuget
  displayName: Package Nuget Project
  type: boolean
  default: true

- name: RunUnitTests
  displayName: Run Unit Tests
  type: boolean
  default: true

- name: RunIntegTests
  displayName: Run Integration Tests
  type: boolean
  default: false

- name: RunSonarCloudTests
  displayName: Run Sonar Cloud Analysis
  type: boolean
  default: true

- name: RunMutationTests
  displayName: Run Mutation Tests
  type: boolean
  default: false

- name: RunACTests
  displayName: Run Acceptance Tests
  type: boolean
  default: false

- name: testSettings
  type: object
  default:
    - name: ApplicationInsights:InstrumentationKey
      value: vh-core-infra-AppInsightsKey
    - name: AzureAd:ClientId
      value: vh-im-api-appid
      secret: true
    - name: AzureAd:ClientSecret
      value: vh-im-api-key
      secret: true
    - name: AzureAd:TenantId
      value: tenantid
      secret: true
    - name: Services:VhimApiResourceId
      value: vh-im-api-identifieruris
      secret: true
    
- name: appSettings
  type: object
  default:
  - name: ApplicationInsights:InstrumentationKey
    value: vh-core-infra-AppInsightsKey
    secret: true
  - name: AzureAd:ClientId
    value: vh-im-api-appid
    secret: true
  - name: AzureAd:ClientSecret
    value: vh-im-api-key
    secret: true
  - name: AzureAd:TenantId
    value: tenantid
    secret: true
  - name: Services:VhimApiResourceId
    value: vh-im-api-identifieruris
    secret: true

  # Connection strings
  - name: ConnectionStrings:VhImApi
    value: vhimDatabaseConnectionString
    secret: true

variables:
  - group: vh-domains-and-urls
  - group: vh-apps-settings-generic
  - group: vh-preview

trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*

pr:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts
  containers:
  - container: dotnetsdk
    image: sspublicsbox.azurecr.io/vh/dotnet:3.1.102
    endpoint: sspublicsbox
  - container: dotnetsdk-cipipeline
    image: sspublicsbox.azurecr.io/vh/dotnet-cipipeline:3.1.102
    endpoint: sspublicsbox

extends:
  template: stages\dotnet-package.yml@templates
  parameters:
    useNugetConfig: true
    nugetConfigPath: InstantMessagingApi
    coreProjectPath: InstantMessagingApi/InstantMessagingApi
    nugetProjectPath: InstantMessagingApi/InstantMessagingApi.Client
    PackageNuget: ${{ parameters.PackageNuget }}
    PackageApp: ${{ parameters.PackageApp }}
    PackageAcceptanceTests: ${{ parameters.PackageACTests }}
    Test: ${{ or(parameters.RunUnitTests, parameters.RunIntegTests, parameters.RunMutationTests) }}
    testParameters:
      baseAgent: windows-latest
      coreProjectPath: InstantMessagingApi/InstantMessagingApi
      useNugetConfig: true
      nugetConfigPath: InstantMessagingApi
      unitTestProjectPath: InstantMessagingApi/InstantMessagingApi.UnitTests
      integTestProjectPath: InstantMessagingApi/InstantMessagingApi.IntegrationTests
      secrets_KeyVault: $(pr_Secret_KeyVault)
      secrets_Subscription: $(pr_Secret_Subscription)
      RunUnitTests: ${{ parameters.RunUnitTests }}
      RunIntegrationTests: ${{ parameters.RunIntegTests }}
      RunSonarCloud: ${{ parameters.RunSonarCloudTests }}
      RunStryker: ${{ parameters.RunMutationTests }}
      IntegrationTestSettings:
        - ${{ each setting in parameters.testSettings }}:
          - name: ${{ setting.name }}
            value: ${{ setting.value }}
            secret: ${{ setting.secret }}
            type: ${{ setting.type }}
      variables:
        - group: vh-im-api
      coverletCoverageExclusions:
        - "[InstantMessagingApi.*Tests?]*"
        - "[InstantMessagingApi]Startup"
        - "[InstantMessagingApi.Common]*"
        - "[Testing.Common]*"
      sonarCloud_ExtraProperties: |
        sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)/Coverage/coverage.opencover.xml
        sonar.coverage.exclusions=**/InstantMessagingApi/Swagger/**/*,**/Program.cs,**/Startup.cs,**/Testing.Common/**/*,**/InstantMessagingApi.Common/**/*,**/InstantMessagingApi.IntegrationTests/**/*,**/InstantMessagingApi.UnitTests/**/*,**/InstantMessagingApi/Extensions/*,**/InstantMessagingApi.DAL/Migrations/**/*
        sonar.cpd.exclusions=**/Program.cs,**/InstantMessagingType.cs,**/Startup.cs,**/Testing.Common/**/*,**/InstantMessagingApi/Swagger/**/*,InstantMessagingApi/InstantMessagingApi.DAL/Migrations/*
      StrykerBreak: 75
    ACTest: ${{ parameters.RunACTests }}
    releaseParameters:
      environment: Preview
      subscription: $(pr_Subscription)
      secrets_KeyVault: $(pr_Secret_KeyVault)
      secrets_Subscription: $(pr_Secret_Subscription)
      devOpsResource: vh_InstantMessaging_api
      appName: vh-im-api-$(environment)
      resourceGroup: vh-im-api-$(environment)
      appSettings: ${{ parameters.appSettings }}
      variables:
        - group: vh-im-api
      acceptanceTestSettings:
        - name: Services:InstantMessagingApiUrl
          value: $(InstantMessaging_api_url_staging)
        - ${{ each setting in parameters.testSettings }}:
          - name: ${{ setting.name }}
            value: ${{ setting.value }}
            secret: ${{ setting.secret }}
